name: royalcruiser
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#version: 3.0.1+56
#iOS
version: 3.0.7+60

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  store_redirect:
  get: ^4.3.6
  shared_preferences: ^2.0.6
  package_info: ^2.0.2
  connectivity:
  platform_device_id:
  intl: ^0.17.0
  dio: ^4.0.6
  http: ^0.13.4
  xml: ^5.1.0
  webview_flutter: ^2.0.4
  flutter_widget_from_html: ^0.8.5
  autocomplete_textfield: ^1.7.3
  photo_view: ^0.13.0
  logger: ^1.1.0
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  flutter_share:
  flutter_spinkit: ^5.0.0
  animated_bottom_navigation_bar: ^1.1.0
  lottie: ^2.3.2
  shimmer: ^2.0.0
  ticketview:
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  flutter_linkify: ^6.0.0
  url_launcher:
  flutter_html: ^2.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.10.0

flutter_icons:
    image_path: 'assets/images/ic_launcher.png'
    ios: true
    android: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/insurance/
    - assets/fonts/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open-Sans-Bold
      fonts:
        - asset: assets/fonts/Open-Sans-Bold.ttf
    - family: Open-Sans-Regular
      fonts:
        - asset: assets/fonts/Open-Sans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
